#!/usr/bin/env python

import pygtk
pygtk.require("2.0")

import os, sys, gtk, gtk.glade, gobject, cairo, pango, goocanvas, math
import opensim.visuals as sim


class OpenSimGTK(gobject.GObject):

  def drawing_tool_toggled(self, widget):

    # if a widget is being un-toggled, then we don't have
    # to worry about it (otherwise breaks toggle effect)
    if widget.get_active() == False:
      # make sure we catch the case where no tool is active.
      if widget.type == self.canvas.get_active_tool():
        self.canvas.set_active_tool(sim.NONE)
        if self.canvas.goocanvas.highlighted:
          self.canvas.goocanvas.highlighted.emit("highlight_out_event", self)
      return

    # switch between possible widgets.
    if widget.type != sim.VARIABLE:
      self.button_variable.set_active(False)    
    if widget.type != sim.INFLUENCE:
      self.button_influence.set_active(False)
    if widget.type != sim.STOCK:
      self.button_stock.set_active(False)
    if widget.type != sim.FLOW:
      self.button_flow.set_active(False)

    # let the canvas know what tool is active
    self.canvas.set_active_tool(widget.type)


  def __init__(self, **kwargs):
    super(OpenSimGTK, self).__init__(**kwargs)

    pathname = os.path.dirname(sys.argv[0])
    abspathname = os.path.abspath(pathname)
    #Set and load the Glade file
    self.gladefile = os.path.join(abspathname, "opensim-main.glade")
    self.wTree = gtk.glade.XML(self.gladefile) 

    #Get the Main Window, and connect the "destroy" event
    self.window = self.wTree.get_widget("main_window")

    dic = {"on_drawing_tool_toggled" : self.drawing_tool_toggled, 
           "on_open" : self.open_clicked,
           "on_save" : self.save_clicked,
           "on_save_as" : self.save_as_clicked,
           "on_main_window_destroy" : gtk.main_quit, 
           "on_file_quit" : gtk.main_quit}
    self.wTree.signal_autoconnect(dic)
    
    #Get our 4 buttons & add type attributes to them
    self.button_variable = self.wTree.get_widget("but_variable")
    self.button_variable.type = sim.VARIABLE
    self.button_influence = self.wTree.get_widget("but_influence")
    self.button_influence.type = sim.INFLUENCE
    self.button_stock = self.wTree.get_widget("but_stock")
    self.button_stock.type = sim.STOCK
    self.button_flow = self.wTree.get_widget("but_flow")
    self.button_flow.type = sim.FLOW

    #insert our goocanvas (since I don't want to deal with 
    #getting it working with glade just yet...)
    main_vbox = self.wTree.get_widget("main_vbox")
    main_tool_bar = self.wTree.get_widget("main_tool_bar")

    self.canvas = sim.Canvas()
    self.status_bar = gtk.Statusbar()

    main_vbox.pack_start(self.canvas, True, True, 0)
    main_vbox.pack_start(self.status_bar, False, False, 0)

    self.canvas.show()
    self.status_bar.show()

  def save_clicked(self, widget):
    print "** save clicked **"
    pass

  def save_as_clicked(self, widget):
    print "** save as clicked **"
    pass

  def open_clicked(self, widget):
    dialog = gtk.FileChooserDialog(title="Open Existing Model...",
                                   action=gtk.FILE_CHOOSER_ACTION_OPEN,
                                   buttons=(gtk.STOCK_CANCEL,
                                            gtk.RESPONSE_CANCEL,
                                            gtk.STOCK_OPEN,gtk.RESPONSE_OK))
    dialog.set_default_response(gtk.RESPONSE_OK)
   
    filter = gtk.FileFilter()
    filter.set_name("Models")
    filter.add_pattern("*.osm")
    filter.add_pattern("*.mdl")
    dialog.add_filter(filter)

    filter = gtk.FileFilter()
    filter.set_name("All files")
    filter.add_pattern("*")
    dialog.add_filter(filter)   
   
    response = dialog.run()
    if response == gtk.RESPONSE_OK:
      print dialog.get_filename(), 'selected'
    elif response == gtk.RESPONSE_CANCEL:
      print 'Closed, no files selected'
    dialog.destroy()


  def write_file(self, file_path):
    '''
    Implement this method to save your activity's state.
    '''
    logging.debug('writing file')
    self.canvas.save_model(file_path)

    
  def read_file(self, file_path):
    '''
    Implement this method to resume state saved in write_file().
    '''
    logging.debug('reading file')
    #f = open(file_path, 'r')
    #try:
    self.canvas.open_model(file_path)
      #print('**opened**')
      #print f
      #print('**contents:**')
      #for line in f.readlines():
      #  print line,
      #print('**closed**')
    #finally:
    #  f.close()


  def main(self):
    gtk.main()



gobject.type_register(OpenSimGTK)


if __name__ == "__main__":
  gui = OpenSimGTK()
  gui.main()
